### ISSUE TITLE
Rol del firmante

### ISSUE THREAD

**Issue by JMLOSP** [ctt-gob-es/FirmaXadesNet#1]
Buenos días,
En primer lugar agradecer el gran trabajo realizado en esta librería es de muchisima utilidad.

Por otro lado consultar lo siguiente:

No encuentro en la librería ningún ejemplo para añadir el rol del firmante que debe de llevar el FacturaE 3.2 para la politica de firma 3.1, 

Según especifica el modelo:

> • El elemento xades:SignerRole, caso de usarse, deberá contener uno y sólo uno de los
> siguientes atributos en el campo ClaimedRoles:
> 
> o “supplier” o “emisor”: cuando la firma de la factura la realiza el emisor.
> o “customer” o “receptor”: cuando la firma de la factura la realiza el receptor.
> o “third party” o “tercero”: cuando la firma la realiza una persona o entidad distinta
> al emisor o al receptor de la factura.

Debiendo quedar algo así en el XML final.

```
                        <xades:SignerRole>
                            <xades:ClaimedRoles>
                                <xades:ClaimedRole>emisor</xades:ClaimedRole>
                            </xades:ClaimedRoles>
                        </xades:SignerRole>
```

¿Existe ya esta funcionalidad o está pensado añadir esta funcionalidad en futuras versiones?

El validador de formato FacturaE y el de la web VALIDe no indican error cuando no lo llevan pero sigue siendo un requisito de la política de firma.

Muchas gracias.

**Comment by dnturbanismo** [comment]
Hola @JMLOSP ,

Acabo de publicar en el otro repositorio que tenemos para el framework 4.5 las modificaciones para el soporte del rol firmante:

https://github.com/ctt-gob-es/FirmaXadesNet45/commit/2d13ae9c9fefb46b7a58b0e7d44846fba861273d

De momento no tengo previsto aplicar las modificaciones a este repositorio, pero no creo que te resulte complicado hacerlo si lo necesitas para esta versión del framework.

Un saludo.

**Comment by JMLOSP** [comment]
Hola @dnturbanismo 

Muchísimas gracias por tu contestación. Voy a bajarme la versión del repositorio 4.5 y a probarlo, como tengo un fork del repositorio actual version 4.0 quizá integre tus modificaciones y te haga un Pull Request ya que para nosotros es importante trabajar con FrameWork 4.0 por metodologia de desarrollo.

Te mantengo informado.

Muchas gracias de nuevo. Saludos.

**Comment by jcaguilar40** [comment]
Hola, excelente tu contribución.
He logrado firma en formato xades-pes , la pregunta es como se hace para que la firma se inserte en una determinada ruta es mi caso en la ruta /ext:UBLExtension/ext:ExtensionContent . y no al final como actualmente me firma.

Gracias de antemano por tu respuesta

**Comment by jcaguilar40** [comment]
Que variacion se tendria que hacer para que el certificado no lo lea desde el repositorio sino del mismo archivo.pfx con su clave respectiva.

Saludos y Dios los bendiga

**Comment by jcaguilar40** [comment]
ya solucioné mis inquietudes. Buen trabajo.
Saludos

**Comment by dnturbanismo** [comment]
Hola @jcaguilar40 ,

Me alegro de que al final hayas podido solucionar tus inquietudes y de que te haya servido la librería para tus propósitos, últimante no tengo mucho tiempo para contestar a los mensajes.

Un saludo.

**Comment by jcaguilar40** [comment]
Gracias. una consulta

Tengo una firma  XAdES-EPES generada con tu libreria  . Resulta que lo que me genera en: QualifyingProperties es:

<xades:QualifyingProperties Id="QualifyingProperties-124a7e6c-a9dc-4fc3-80c0-884686555e1c" Target="#Signature-11c1a486-d356-4648-bc20-a9f2717963f6" xmlns:xades="http://uri.etsi.org/01903/v1.3.2#">

y lo que necesito es generar esto en signature QualifyingProperties :

<xades:QualifyingProperties Id="QualifyingProperties-124a7e6c-a9dc-4fc3-80c0-884686555e1c" Target="#Signature-11c1a486-d356-4648-bc20-a9f2717963f6"  xmlns:xades141="http://uri.etsi.org/01903/v1.4.1#" xmlns:xades="http://uri.etsi.org/01903/v1.3.2#">

Como puedo agregar en la firma: xmlns:xades141="http://uri.etsi.org/01903/v1.4.1#" en QualifyingProperties?

SAludos y gracias por l respuesta

**Comment by dnturbanismo** [comment]
Tienes que modificar el método GetXml de la clase QualifyingProperties para que te devuelva el elemento XML con el espacio de nombre que deseas.

Ten en cuenta que esta librería genera firmas en base a la versión 1.3.2 del esquema.

Saludos.

**Comment by jcaguilar40** [comment]
Estimado, muchas gracias por tu tiempo y respuesta, la verdad recien estoy entrando a ver este teme de firmado con xadex. El problema que se presenta es que debo obtener una firma parecida: a

[cid:6f718a68-1ae0-41f4-abce-69326c3f5311]

Como se podria conseguir eso o darme algunas pistas para poder conseguirlo: la libreria lo soporta? es para el caso de firma del mdelo colombiano.

Atte

José Carlos Aguilar Vásquez

---

De: J. Arturo notifications@github.com
Enviado: lunes, 10 de octubre de 2016 11:07 a.m.
Para: ctt-gob-es/FirmaXadesNet
Cc: jcaguilar40; Mention
Asunto: Re: [ctt-gob-es/FirmaXadesNet] Rol del firmante (#1)

Tienes que modificar el método GetXml de la clase QualifyingProperties para que te devuelva el elemento XML con el espacio de nombre que deseas.

Ten en cuenta que esta librería genera firmas en base a la versión 1.3.2 del esquema.

Saludos.

##

**Comment by jcaguilar40** [comment]
Estimado amigo de verdad gracias por tu respuesta, y abusando de tu generosidad no se si me puedes apoyar con esto:

Es con respecto  al nodo xades:cert        , en tu libreria solo genera uno y ami me exigen 3 de acuerdo a la informacion que te adjunto. la pregunta es de donde saco estos datos

[cid:f6ec7c39-5e5f-46bb-b1a8-bc109f670003]

Vi en que parte insertar, lo que no me queda claro es que información debo insertarla y si esa informacion esta en el certificado o no?

Dios te bendiga.

Atte

 José Carlos Aguilar Vásquez

---

De: J. Arturo notifications@github.com
Enviado: lunes, 10 de octubre de 2016 11:07 a.m.
Para: ctt-gob-es/FirmaXadesNet
Cc: jcaguilar40; Mention
Asunto: Re: [ctt-gob-es/FirmaXadesNet] Rol del firmante (#1)

Tienes que modificar el método GetXml de la clase QualifyingProperties para que te devuelva el elemento XML con el espacio de nombre que deseas.

Ten en cuenta que esta librería genera firmas en base a la versión 1.3.2 del esquema.

Saludos.

##

**Comment by dnturbanismo** [comment]
Hola,

Creo que al responder desde el correo electrónico no se están adjuntando las imágenes y nos las puedo ver.

Saludos.

**Comment by jcaguilar40** [comment]
Estimado, tengo una inquietud:

Firmando con tu libreria los datos del  issuerName me arrojan estos resultados que a mi parecer es el correcto,

C=CO, L="BOGOTÁ, D.C.", STREET=Carrera 21 A No 124 - 55 Oficina 303. https://www.gse.com.co/direccion, OU=http://www.gse.com.co, T=AC GSE S.A., O=GESTION DE SEGURIDAD ELECTRONICA S.A., E=ca@gse.com.co, SERIALNUMBER=NIT 9002042728, CN=SUB001 AC GSE S.A., Description=Certificado Subordinada 001 AC GSE S.A.

Pero firmando con la libreria de otra pagina me arroja lo sgt:

C=CO, L=BOGOTÁ\, D.C., STREET=Carrera 21 A No 124 - 55 Oficina 303. https://www.gse.com.co/direccion, OU=http://www.gse.com.co, 2.5.4.12=#0C0B41432047534520532E412E, O=GESTION DE SEGURIDAD ELECTRONICA S.A., E=ca@gse.com.co, 2.5.4.5=#130E4E49542039303032303432373238, CN=SUB001 AC GSE S.A., 2.5.4.13=#0C27436572746966696361646F205375626F7264696E616461203030312041432047534520532E412E

Se que lo ambos son equivalentes ya que los OID son correctos y los valores estan en hexadecimal (los digestvaule si me arroja lo mismo)

pero la pregunta es como puedo adaptar tu libreria para obtener los datos de la segunda forma ya que el validador (Dian colombia) parece que lo necesita e e segundo formato.

Saludos

Jose Carlos Aguilar Vasquez

**Comment by dnturbanismo** [comment]
Hola,

No entiendo muy bien por que no aceptan la primera forma,...quizás la clase X509Name te pueda ayudar a solucionar tu problema.

Voy a proceder a cerrar el hilo ya que esto no tiene nada que ver con el título.

Saludos.
