### ISSUE TITLE
No veo que soporte XADES-EPES

### ISSUE THREAD

**Issue by sebastianamaro** [ctt-gob-es/FirmaXadesNet#3]
Hola, en el readme indica que soporta XADES-EPES, pero no hay ningun componente dentro de la libreria firmaxadesnet que permita XADES-EPES (Si XADES T y XADES XL)

Hay previsto soporte para XADES-EPES?

**Comment by dnturbanismo** [comment]
Hola,

La información sobre la política de firma se puede añadir usando el parámetro SignaturePolicyInfo, aquí tienes un ejemplo:

https://github.com/ctt-gob-es/FirmaXadesNet/blob/master/DemoFacturae/FrmPrincipal.cs
